services:
  nginx:
    build: nginx
    image: flask-app-nginx:latest
    #env_file: settings.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 32M
    healthcheck:
      test: ['CMD-SHELL', 'curl -sf localhost:80/health-check || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - app
    ports:
      - '80:80'

  app:
    build: app
    image: flask-app:latest
    #env_file: settings.env
    command: 'gunicorn -w 2 -t 60 -b 0.0.0.0:9000 app:app'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
