services:
  nginx:
    build: nginx
    image: flask-app-nginx:latest
    #env_file: settings.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 32M
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ${APP_FILES_STATIC:-./app/static}:/data/static

  app:
    build: app
    image: flask-app:latest
    #env_file: settings.env
    command: 'flask run --host=0.0.0.0 --port=9000'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
    volumes:
      - ${APP_FILES:-./app}:/app
