version: '3.8'

services:
  nginx:
    build: nginx
    image: ghcr.io/smashedr/flask-random-image-nginx:latest
    #env_file: settings.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 32M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.flask-random-image-http.rule=Host(`flask-image.cssnr.com`)
        - traefik.http.routers.flask-random-image-http.entrypoints=http
        - traefik.http.routers.flask-random-image-http.middlewares=https-redirect
        - traefik.http.routers.flask-random-image-https.rule=Host(`flask-image.cssnr.com`)
        - traefik.http.routers.flask-random-image-https.entrypoints=https
        - traefik.http.routers.flask-random-image-https.tls=true
        - traefik.http.services.flask-random-image-https.loadbalancer.server.port=80
    healthcheck:
      test: ['CMD-SHELL', 'curl -sf localhost:80/health-check || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - app
    networks:
      - traefik-public

  app:
    build: app
    image: ghcr.io/smashedr/flask-random-image-app:latest
    #env_file: settings.env
    command: 'gunicorn -w 2 -t 60 -b 0.0.0.0:9000 app:app'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 64M

networks:
  traefik-public:
    external: true
