FROM nginx:mainline

LABEL org.opencontainers.image.source="https://github.com/smashedr/flask-random-image"
LABEL org.opencontainers.image.description="Flask Random Image"
LABEL org.opencontainers.image.authors="smashedr"

ENV TZ=UTC

COPY nginx.conf /etc/nginx/nginx.conf
