name: 'Build'

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./nginx
            image: ghcr.io/${{ github.repository }}-nginx
          - context: ./app
            image: ghcr.io/${{ github.repository }}-app
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Docker Login'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: 'Setup Buildx'
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: 'Docker Metadata'
        id: meta
        uses: docker/metadata-action@v5
        env:
          latest: ${{ ! github.event.release.prerelease && github.event_name == 'release' }}
        with:
          images: ${{ matrix.image }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable=${{ env.latest }}

      - name: 'Debug'
        run: |
          echo "file: ${{ matrix.dockerfile }}"
          echo "image: ${{ matrix.image }}"
          echo "tags: ${{ steps.meta.outputs.tags }}"

      - name: 'Build and Push'
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
